#!/bin/bash
source ./env.sh

cmake -S ${SRCDIR}/quda -B ${BUILDDIR}/build_quda \
	-DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_INSTALL_PREFIX=${QUDA_INSTALLDIR} \
	-DCMAKE_PREFIX_PATH=${PREFIX_PATH} \
	-DQUDA_GPU_ARCH=${SM} \
	-DQUDA_NVSHMEM=${QUDA_NVSHMEM} \
	-DQUDA_DIRAC_DEFAULT_OFF=ON \
	-DQUDA_DIRAC_CLOVER=ON \
	-DQUDA_DIRAC_WILSON=ON \
	-DQUDA_INTERFACE_QDPJIT=ON \
	-DQUDA_QDPJIT=ON \
	-DQUDA_INTERFACE_MILC=OFF \
	-DQUDA_INTERFACE_CPS=OFF \
	-DQUDA_INTERFACE_QDP=ON \
	-DQUDA_INTERFACE_TIFR=OFF \
	-DQUDA_QMP=ON \
	-DQUDA_QIO=OFF \
	-DQUDA_MULTIGRID=ON \
	-DQUDA_MAX_MULTI_BLAS_N=9 \
	-DQUDA_BUILD_SHAREDLIB=ON \
	-DQUDA_BUILD_ALL_TESTS=OFF \
	-DLLVM_DIR=${LLVM_INSTALLDIR}/lib/cmake/llvm \
	-DQMP_DIR=${QMP_INSTALLDIR}/lib/cmake/QMP/ \
	-DQDPXX_DIR=${QDPJIT_INSTALLDIR}/lib/cmake/QDPXX \
	-DCMAKE_CXX_FLAGS=${ARCHFLAGS}

cmake --build ${BUILDDIR}/build_quda ${CMAKE_MAKE_OPTS}
cmake --install ${BUILDDIR}/build_quda
