

. ./env-MODULES.sh

##### 
# SET UP ENVIRONMENT

#export CMAKE_C_COMPILER=mpicc
#export CMAKE_CXX_COMPILER=mpicxx
#export CMAKE_ASM_COMPILER=gcc


export CMAKE_GENERATOR=Ninja
# if not using Ninja please
#xport CMAKE_MAKE_OPTS="-- -j$(nproc)"

SM=sm_80     # Ampere
# use NVSHMEM
QUDA_NVSHMEM=OFF # or ON 
QDPJIT_HOST_ARCH="X86;NVPTX"

### COMPILER FLAGS
ARCHFLAGS="-march=native"
DEBUGFLAGS=" "

# some directories
TOPDIR=`pwd`
SRCDIR=${TOPDIR}/SRC/
BUILDDIR=${TOPDIR}/BUILD/
INSTALLDIR=${TOPDIR}/INSTALL/


LLVM_INSTALLDIR=${INSTALLDIR}/LLVM/
QMP_INSTALLDIR=${INSTALLDIR}/QMP/
QDPJIT_INSTALLDIR=${INSTALLDIR}/QDP-JIT/
QUDA_INSTALLDIR=${INSTALLDIR}/QUDA/
CHROMA_INSTALLDIR=${INSTALLDIR}/CHROMA/



PREFIX_PATH="${LLVM_INSTALLDIR}:${QMP_INSTALLDIR}:${QDPJIT_INSTALLDIR}:${QUDA_INSTALLDIR}"

export CMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}:${PREFIX_PATH}


